green="\e[0;92m"
blue="\e[0;94m"
yellow="\e[0;33m"
echo ""
echo ""
echo -e "${green}Goob mc Doob"
echo -e "${green}Doob mc Goob"
echo -e "${blue}Goob mc Doob"
echo -e "${blue}Doob mc Goob"
echo -e "${yellow}Goob mc Doob"
echo -e "${yellow}Doob mc Goob"
echo ""
echo ""
