green="\e[0;92m"
blue="\e[0;94m"
yellow="\e[0;33m"
white="\e[0;97m"
red="\e[0;91m"

echo ""
echo ""
echo -e "${blue}Goob mc Doob"
echo -e "${blue}Doob mc Goob"
echo -e "${white}Goob mc Doob"
echo -e "${white}Doob mc Goob"
echo -e "${red}Goob mc Doob"
echo -e "${red}Doob mc Goob"
echo -e "${green}Goob mc Doob"
echo -e "${green}Doob mc Goob"
echo -e "${blue}Goob mc Doob"
echo -e "${blue}Doob mc Goob"
echo -e "${yellow}Goob mc Doob"
echo -e "${yellow}Doob mc Goob"
echo -e "${white}Goob mc Doob"
echo -e "${white}Doob mc Goob"
echo -e "${red}Goob mc Doob"
echo -e "${red}Doob mc Goob"
echo ""
echo -e "${green}Download the goob here: https://github.com/XanderIsBored/ominous-goob"
echo ""
echo ""
